services:
  gringotts:
    build:
      context: .
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    container_name: gringotts
    restart: unless-stopped
    ports:
      # On expose sur le port 3001 de ton serveur (pour ne pas interférer avec CinePrivé qui est sûrement sur le 3000)
      - "3001:80"
    env_file:
      - .env
