server {
    # Bloque les accès directs par IP
    listen 80 default_server;
    server_name _;
    return 444; # Ferme la connexion sans répondre
}

server {
    listen 80;
    # Accepte uniquement les requêtes pour le vrai nom de domaine et localhost
    server_name rpisimon.uk www.rpisimon.uk localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Redirection pour que le routeur SPA (React) fonctionne correctement
        try_files $uri $uri/ /index.html;
    }

    # Headers de sécurité
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    # Stratégie de cache pour les assets statiques
    location ~* \.(?:css|js|woff2?|svg|gif|map)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Pas de cache pour le service worker
    location = /sw.js {
        root /usr/share/nginx/html;
        add_header Cache-Control "no-cache";
    }
    
    # Pas de cache pour index.html pour s'assurer des mises à jour
    location = /index.html {
        root /usr/share/nginx/html;
        add_header Cache-Control "no-cache";
    }
}
